WEIGHT_INIT = 0.01
NUM_TASKS = 3
IMG_SIZE = 48
INIT_LR = 0.01
USE_BN = True
BN_DECAY = 0.99
EPSILON = 0.001
WEIGHT_DECAY = 0.001
DECAY_STEP = 10000
DECAY_LR_RATE = 0.8
BATCH_SIZE = 256

USE_GPU = True
SAVE_FOLDER = './save_model/is_running/'
BEST_MODEL = './save_model/best_model/'

SAVE_FOLDER2 = './save_model/origin_model/'
NUM_EPOCHS = 2000
DROP_OUT_PROB = 0.5


NUMBER_DUPLICATE_SMILE = 10